### ISSUE TITLE
feature suggestion

### ISSUE THREAD

**Issue by gouchaoer** [deepziyu/yii2-swoole#3]
1，mysql的事务swoole那边刚merge，新版本放出了可以考虑加上
2，文件操作可以考虑一下aio
3，可以考虑带上个dockerfile

**Comment by deepziyu** [comment]
是的，mysql事务要加上，现在看源码，因为没有文档。

**Comment by deepziyu** [comment]
MySQL 事务已经实现。
文件日志目前是 aio 的，用户如果要异步操作文件，应该按 swoole 文档上操作即可，过多封装无益。
dokerfile 得等 swoole2 稳定版发出再做啦。
