### ISSUE TITLE
这里至少把\也替换了

### ISSUE THREAD

**Issue by gouchaoer** [deepziyu/yii2-swoole#6]
https://github.com/deepziyu/yii2-swoole/blob/5cb8162a35d5a34b5b2bd447b875e4943a464c8a/db/MysqlPoolPdo.php#L188

https://stackoverflow.com/questions/11597025/is-this-use-of-str-replace-sufficient-to-prevent-sql-injection-attacks

**Comment by deepziyu** [comment]
这个不打算修复了，等 mysql::prepare 出来。
Rango-韩天峰 2017/11/14 12:21:08
下个版本增加 channel，mysql prepare，user coroutinr

**Comment by deepziyu** [comment]
已经修复，fix it
